{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hc-data-platform.backendServiceAccountName" . }}
  labels:
    {{- include "hc-data-platform.labels" . | nindent 4 }}
  {{- with .Values.backend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
