{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hc-data-platform.fullname" . }}-default-deny-ingress
  labels:
    {{- include "hc-data-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hc-data-platform.fullname" . }}-allow-gateway
  labels:
    {{- include "hc-data-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: [frontend, api]
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingressController.namespaceSelector | nindent 12 }}
          {{- with .Values.networkPolicy.ingressController.podSelector }}
          podSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.frontend.port }}
        - protocol: TCP
          port: {{ .Values.backend.api.port }}
{{- end }}
