{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hc-data-platform.fullname" . }}-frontend
  labels:
    {{- include "hc-data-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.podDisruptionBudget.frontendMinAvailable }}
  selector:
    matchLabels:
      {{- include "hc-data-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
{{- end }}

