services:
  migration:
    build:
      context: /home/hc_op/workspace/openarm-integration/B/platform/backend
      dockerfile: ../artifacts/g0/Dockerfile.offline
      target: null
  postgres:
    image: hc-offline/postgres:71eaa560
  temporal:
    image: hc-offline/temporal:71eaa560
  minio:
    image: hc-offline/minio:71eaa560
  minio-init:
    image: hc-offline/mc:71eaa560
