"""Stable Temporal registration names shared by clients, workflows, and workers."""

PARSE_MANIFEST_ACTIVITY = "workflow.parse_manifest"
VERIFY_RAW_ACTIVITY = "workflow.verify_raw"
PROCESS_INGEST_SOURCE_ACTIVITY = "workflow.process_ingest_source"
MATERIALIZE_INGEST_PROJECTION_ACTIVITY = "workflow.materialize_ingest_projection"
CLEANUP_INGEST_PROJECTION_ACTIVITY = "workflow.cleanup_ingest_projection"
EVALUATE_QUALITY_ACTIVITY = "workflow.evaluate_quality"
ALIGN_FRAGMENT_ACTIVITY = "workflow.align_fragment"
COMMIT_FRAGMENT_ACTIVITY = "workflow.commit_fragment"
COMMIT_ALIGNED_BUNDLE_ACTIVITY = "workflow.commit_aligned_bundle"
CLEANUP_ALIGNMENT_STAGING_ACTIVITY = "workflow.cleanup_alignment_staging"
CREATE_ANNOTATION_TASK_ACTIVITY = "workflow.create_annotation_task"
CREATE_ALIGNED_MEDIA_ACTIVITY = "workflow.create_aligned_media"
CLEANUP_UNCOMMITTED_ALIGNED_MEDIA_ACTIVITY = "workflow.cleanup_uncommitted_aligned_media"
PUBLISH_DATASET_ACTIVITY = "workflow.publish_dataset"
EXPORT_DATASET_ACTIVITY = "workflow.export_dataset"
PREFLIGHT_EXPORT_ACTIVITY = "workflow.preflight_export"
VERIFY_EXPORT_ARTIFACT_ACTIVITY = "workflow.verify_export_artifact"
RECONCILE_CATALOG_ACTIVITY = "workflow.reconcile_catalog"
RECONCILE_PUBLICATION_ACTIVITY = "workflow.reconcile_publication"
PERSIST_WORKFLOW_JOB_ACTIVITY = "workflow.persist_job"

INGEST_ROLLOUT_WORKFLOW = "IngestRolloutWorkflow"
DATASET_WRITER_WORKFLOW = "DatasetWriterWorkflow"
PUBLISH_DATASET_WORKFLOW = "PublishDatasetWorkflow"
EXPORT_WORKFLOW = "ExportWorkflow"
CATALOG_RECONCILIATION_WORKFLOW = "CatalogReconciliationWorkflow"
PUBLISH_RECONCILIATION_WORKFLOW = "PublishReconciliationWorkflow"
ANNOTATION_REVIEW_PREPARATION_WORKFLOW = "AnnotationReviewPreparationWorkflow"
