import type { ThemeConfig } from "antd";
import { platformTokens as tokens } from "./tokens";

const focusShadow = `0 0 0 3px ${tokens.color.focus}55`;

export const uiTheme: ThemeConfig = {
  inherit: false,
  cssVar: { prefix: "hc", key: "hc-platform" },
  token: {
    colorPrimary: tokens.color.primary,
    colorPrimaryHover: tokens.color.primaryHover,
    colorPrimaryActive: tokens.color.primaryActive,
    colorInfo: tokens.color.info,
    colorInfoText: tokens.color.infoText,
    colorSuccess: tokens.color.success,
    colorSuccessText: tokens.color.successText,
    colorWarning: tokens.color.warning,
    colorWarningText: tokens.color.warningText,
    colorError: tokens.color.error,
    colorErrorText: tokens.color.errorText,
    colorBgLayout: tokens.color.page,
    colorBgContainer: tokens.color.surface,
    colorBgElevated: tokens.color.surface,
    colorBorder: tokens.color.border,
    colorBorderSecondary: tokens.color.borderSubtle,
    colorText: tokens.color.text,
    colorTextSecondary: tokens.color.textMuted,
    colorTextTertiary: tokens.color.textMuted,
    fontWeightStrong: 650,
    borderRadiusXS: tokens.radius.xs,
    borderRadiusSM: tokens.radius.sm,
    borderRadius: tokens.radius.md,
    borderRadiusLG: tokens.radius.lg,
    controlHeightSM: tokens.controlHeight.sm,
    controlHeight: tokens.controlHeight.md,
    controlHeightLG: tokens.controlHeight.lg,
    fontFamily: tokens.typography.fontFamily,
    fontSize: tokens.typography.fontSize,
    fontSizeSM: tokens.typography.fontSizeSm,
    fontSizeLG: tokens.typography.fontSizeLg,
    lineHeight: tokens.typography.lineHeight,
    lineHeightHeading1: tokens.typography.lineHeightHeading,
    lineHeightHeading2: tokens.typography.lineHeightHeading,
    lineHeightHeading3: tokens.typography.lineHeightHeading,
    motionDurationFast: "0.14s",
    motionDurationMid: "0.2s",
    motionDurationSlow: "0.28s",
    paddingXXS: tokens.spacing.xs,
    paddingXS: tokens.spacing.sm,
    paddingSM: tokens.spacing.md,
    padding: tokens.spacing.lg,
    paddingMD: tokens.spacing.lg,
    paddingLG: tokens.spacing.xl,
    marginXXS: tokens.spacing.xs,
    marginXS: tokens.spacing.sm,
    marginSM: tokens.spacing.md,
    margin: tokens.spacing.lg,
    marginMD: tokens.spacing.lg,
    marginLG: tokens.spacing.xl,
    controlOutline: `${tokens.color.focus}55`,
    controlOutlineWidth: 3,
    boxShadow: tokens.shadow.md,
    boxShadowSecondary: tokens.shadow.lg,
    zIndexPopupBase: tokens.zIndex.popup,
    screenXS: tokens.breakpoint.compact,
    screenXSMin: tokens.breakpoint.compact,
    screenXSMax: tokens.breakpoint.tablet - 1,
    screenSM: tokens.breakpoint.tablet,
    screenSMMin: tokens.breakpoint.tablet,
    screenSMMax: tokens.breakpoint.desktop - 1,
    screenMD: tokens.breakpoint.desktop,
    screenMDMin: tokens.breakpoint.desktop,
    screenMDMax: 1199,
    screenLG: 1200,
    screenLGMin: 1200,
    screenLGMax: tokens.breakpoint.wide - 1,
    screenXL: tokens.breakpoint.wide,
    screenXLMin: tokens.breakpoint.wide,
    screenXLMax: 1599,
    screenXXL: 1600,
    screenXXLMin: 1600,
  },
  components: {
    Button: {
      borderRadius: tokens.radius.md,
      controlHeight: tokens.controlHeight.md,
      paddingInline: tokens.spacing.lg,
      primaryShadow: "0 8px 20px rgb(89 101 216 / 25%)",
      defaultShadow: tokens.shadow.sm,
      fontWeight: 600,
    },
    Input: {
      borderRadius: tokens.radius.md,
      controlHeight: tokens.controlHeight.md,
      paddingInline: tokens.spacing.md,
      paddingBlock: 6,
      hoverBorderColor: tokens.color.primaryHover,
      activeBorderColor: tokens.color.primary,
      activeShadow: focusShadow,
    },
    Select: {
      borderRadius: tokens.radius.md,
      controlHeight: tokens.controlHeight.md,
      optionHeight: 32,
      optionPadding: `${tokens.spacing.xs}px ${tokens.spacing.md}px`,
      optionActiveBg: tokens.color.surfaceMuted,
      optionSelectedBg: tokens.color.surfaceTint,
      hoverBorderColor: tokens.color.primaryHover,
      activeBorderColor: tokens.color.primary,
      activeOutlineColor: `${tokens.color.focus}55`,
      zIndexPopup: tokens.zIndex.popup,
    },
    Table: {
      borderColor: tokens.color.border,
      headerBg: "#eef0fb",
      headerColor: tokens.color.text,
      headerBorderRadius: tokens.radius.lg,
      rowHoverBg: "#f2f3ff",
      rowSelectedBg: "#e6e8ff",
      rowSelectedHoverBg: "#dfe2ff",
      cellPaddingBlock: 11,
      cellPaddingInline: 14,
      cellPaddingBlockMD: 9,
      cellPaddingInlineMD: 14,
      cellPaddingBlockSM: 8,
      cellPaddingInlineSM: 12,
      cellFontSize: tokens.typography.fontSize,
      cellFontSizeMD: tokens.typography.fontSize,
      cellFontSizeSM: tokens.typography.fontSizeSm,
      headerSplitColor: tokens.color.border,
    },
    Modal: {
      borderRadiusLG: 22,
      contentBg: tokens.color.surface,
      headerBg: tokens.color.surface,
      footerBg: tokens.color.surface,
    },
    Drawer: {
      colorBgElevated: tokens.color.surface,
      zIndexPopup: tokens.zIndex.modal,
      paddingLG: 18,
    },
    Menu: {
      itemBorderRadius: 12,
      subMenuItemBorderRadius: 10,
      itemSelectedBg: "#e5e7ff",
      itemSelectedColor: tokens.color.primaryActive,
      itemHoverBg: "#eef0fb",
      itemHoverColor: tokens.color.primaryActive,
      activeBarBorderWidth: 0,
    },
    Notification: {
      zIndexPopup: tokens.zIndex.toast,
      width: 360,
      colorSuccessBg: "#eff8f4",
      colorWarningBg: "#fff8e8",
      colorErrorBg: "#fff1f0",
      colorInfoBg: "#eef3ff",
    },
    Card: {
      bodyPadding: 22,
      bodyPaddingSM: 18,
      headerPadding: 22,
      headerPaddingSM: 18,
    },
    Tag: {
      borderRadiusSM: 999,
    },
    Segmented: {
      itemSelectedBg: tokens.color.surface,
      itemHoverBg: "#e9ebf7",
      trackBg: "#eceef6",
      trackPadding: 4,
    },
  },
};
