import type { ThemeConfig } from 'antd';
import { platformTokens as tokens } from './tokens';

const focusShadow = `0 0 0 3px ${tokens.color.focus}55`;

export const uiTheme: ThemeConfig = {
  inherit: false,
  cssVar: { prefix: 'hc', key: 'hc-platform' },
  token: {
    colorPrimary: tokens.color.primary,
    colorPrimaryHover: tokens.color.primaryHover,
    colorPrimaryActive: tokens.color.primaryActive,
    colorInfo: tokens.color.info,
    colorSuccess: tokens.color.success,
    colorWarning: tokens.color.warning,
    colorError: tokens.color.error,
    colorBgLayout: tokens.color.page,
    colorBgContainer: tokens.color.surface,
    colorBgElevated: tokens.color.surface,
    colorBorder: tokens.color.border,
    colorBorderSecondary: tokens.color.borderSubtle,
    colorText: tokens.color.text,
    colorTextSecondary: tokens.color.textMuted,
    colorTextTertiary: tokens.color.textMuted,
    borderRadiusXS: tokens.radius.xs,
    borderRadiusSM: tokens.radius.sm,
    borderRadius: tokens.radius.md,
    borderRadiusLG: tokens.radius.lg,
    controlHeightSM: tokens.controlHeight.sm,
    controlHeight: tokens.controlHeight.md,
    controlHeightLG: tokens.controlHeight.lg,
    fontFamily: tokens.typography.fontFamily,
    fontSize: tokens.typography.fontSize,
    fontSizeSM: tokens.typography.fontSizeSm,
    fontSizeLG: tokens.typography.fontSizeLg,
    lineHeight: tokens.typography.lineHeight,
    lineHeightHeading1: tokens.typography.lineHeightHeading,
    lineHeightHeading2: tokens.typography.lineHeightHeading,
    lineHeightHeading3: tokens.typography.lineHeightHeading,
    paddingXXS: tokens.spacing.xs,
    paddingXS: tokens.spacing.sm,
    paddingSM: tokens.spacing.md,
    padding: tokens.spacing.lg,
    paddingMD: tokens.spacing.lg,
    paddingLG: tokens.spacing.xl,
    marginXXS: tokens.spacing.xs,
    marginXS: tokens.spacing.sm,
    marginSM: tokens.spacing.md,
    margin: tokens.spacing.lg,
    marginMD: tokens.spacing.lg,
    marginLG: tokens.spacing.xl,
    controlOutline: `${tokens.color.focus}55`,
    controlOutlineWidth: 3,
    boxShadow: tokens.shadow.md,
    boxShadowSecondary: tokens.shadow.lg,
    zIndexPopupBase: tokens.zIndex.popup,
    screenXS: tokens.breakpoint.compact,
    screenXSMin: tokens.breakpoint.compact,
    screenXSMax: tokens.breakpoint.tablet - 1,
    screenSM: tokens.breakpoint.tablet,
    screenSMMin: tokens.breakpoint.tablet,
    screenSMMax: tokens.breakpoint.desktop - 1,
    screenMD: tokens.breakpoint.desktop,
    screenMDMin: tokens.breakpoint.desktop,
    screenMDMax: 1199,
    screenLG: 1200,
    screenLGMin: 1200,
    screenLGMax: tokens.breakpoint.wide - 1,
    screenXL: tokens.breakpoint.wide,
    screenXLMin: tokens.breakpoint.wide,
    screenXLMax: 1599,
    screenXXL: 1600,
    screenXXLMin: 1600,
  },
  components: {
    Button: {
      borderRadius: tokens.radius.md,
      controlHeight: tokens.controlHeight.md,
      paddingInline: tokens.spacing.md,
      primaryShadow: 'none',
      defaultShadow: 'none',
      fontWeight: 560,
    },
    Input: {
      borderRadius: tokens.radius.md,
      controlHeight: tokens.controlHeight.md,
      paddingInline: tokens.spacing.md,
      paddingBlock: 6,
      hoverBorderColor: tokens.color.primaryHover,
      activeBorderColor: tokens.color.primary,
      activeShadow: focusShadow,
    },
    Select: {
      borderRadius: tokens.radius.md,
      controlHeight: tokens.controlHeight.md,
      optionHeight: 32,
      optionPadding: `${tokens.spacing.xs}px ${tokens.spacing.md}px`,
      optionActiveBg: tokens.color.surfaceMuted,
      optionSelectedBg: '#dff3ee',
      hoverBorderColor: tokens.color.primaryHover,
      activeBorderColor: tokens.color.primary,
      activeOutlineColor: `${tokens.color.focus}55`,
      zIndexPopup: tokens.zIndex.popup,
    },
    Table: {
      borderColor: tokens.color.border,
      headerBg: tokens.color.surfaceMuted,
      headerColor: tokens.color.text,
      headerBorderRadius: tokens.radius.lg,
      rowHoverBg: '#f3f9f8',
      rowSelectedBg: '#e6f5f2',
      rowSelectedHoverBg: '#dcf0ec',
      cellPaddingBlock: tokens.spacing.sm,
      cellPaddingInline: tokens.spacing.md,
      cellPaddingBlockMD: 6,
      cellPaddingInlineMD: tokens.spacing.md,
      cellPaddingBlockSM: tokens.spacing.xs,
      cellPaddingInlineSM: tokens.spacing.sm,
      cellFontSize: tokens.typography.fontSize,
      cellFontSizeMD: tokens.typography.fontSize,
      cellFontSizeSM: tokens.typography.fontSizeSm,
      headerSplitColor: tokens.color.border,
    },
    Modal: {
      borderRadiusLG: tokens.radius.lg,
      contentBg: tokens.color.surface,
      headerBg: tokens.color.surface,
      footerBg: tokens.color.surface,
    },
    Drawer: {
      colorBgElevated: tokens.color.surface,
      zIndexPopup: tokens.zIndex.modal,
      paddingLG: 18,
    },
    Menu: {
      itemBorderRadius: tokens.radius.md,
      subMenuItemBorderRadius: tokens.radius.md,
      itemSelectedBg: '#e8f5f3',
      itemSelectedColor: tokens.color.primaryActive,
      itemHoverBg: '#f3f8f7',
      itemHoverColor: tokens.color.primaryActive,
      activeBarBorderWidth: 0,
    },
    Notification: {
      zIndexPopup: tokens.zIndex.toast,
      width: 360,
      colorSuccessBg: '#effaf5',
      colorWarningBg: '#fff8e8',
      colorErrorBg: '#fff1f0',
      colorInfoBg: '#edf8fc',
    },
  },
};
