# generated by datamodel-codegen:
#   filename:  ingest-schemas.json
#   timestamp: 2026-08-10T17:22:22+00:00

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import (
    AfterValidator,
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    constr,
)

from app.core.int64 import ByteCount


class P02P04IngestContractSchemas(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )


class Id(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Za-z][A-Za-z0-9._:-]{2,127}$")]


class DecimalString(RootModel[ByteCount]):
    """Unsigned int64 represented as a canonical decimal string on the wire."""

    root: ByteCount


class Sha256(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-f0-9]{64}$")]


class IsoDateTime(RootModel[AwareDatetime]):
    root: AwareDatetime


class ETag(RootModel[str]):
    root: Annotated[str, Field(max_length=256, min_length=3)]


def _safe_relative_path(value: str) -> str:
    if value.startswith("/") or ".." in value.split("/"):
        raise ValueError("path must be relative and cannot contain parent traversal")
    return value


class RelativePath(RootModel[str]):
    root: Annotated[
        str,
        Field(min_length=1, max_length=2048, pattern="^[A-Za-z0-9._/-]+$"),
        AfterValidator(_safe_relative_path),
    ]


class Scope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    organization_id: Id
    project_id: Id
    region_code: Annotated[str, Field(pattern="^[a-z0-9]+(?:-[a-z0-9]+)+$")]


class PageInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    has_next_page: Annotated[
        bool,
        Field(description="Whether end_cursor can be sent as the next request's after value."),
    ]
    has_previous_page: Annotated[
        bool,
        Field(description="Whether start_cursor can be sent as the next request's before value."),
    ]
    start_cursor: Annotated[
        str | None,
        Field(description="Opaque boundary value for the before request field."),
    ]
    end_cursor: Annotated[
        str | None,
        Field(description="Opaque boundary value for the after request field."),
    ]


class DataSourcePageQuery(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    after: Annotated[str | None, Field(min_length=1)] = None
    before: Annotated[str | None, Field(min_length=1)] = None
    limit: Literal[10, 20, 50] = 20


class ActorSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None
    display_name: Annotated[str, Field(max_length=200, min_length=1)]


class BlockedReason(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(max_length=100, min_length=1)]
    message: Annotated[str, Field(max_length=500, min_length=1)]


class SafeError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(max_length=100, min_length=1)]
    message: Annotated[str, Field(max_length=1000, min_length=1)]
    retryable: bool
    request_id: str | None = None


class FieldError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: Annotated[str, Field(pattern="^/")]
    code: Annotated[str, Field(min_length=1)]
    message: Annotated[str, Field(min_length=1)]


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(min_length=1)]
    message: Annotated[str, Field(min_length=1)]
    field_errors: list[FieldError]
    operation_errors: list[SafeError]
    blocked_reasons: list[BlockedReason]
    request_id: Id
    retryable: bool


class ErrorEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: Error


class AdministrativeState(RootModel[Literal["DISABLED", "ENABLED"]]):
    root: Literal["DISABLED", "ENABLED"]


class CredentialState(
    RootModel[
        Literal[
            "NOT_REQUIRED",
            "MISSING",
            "CONFIGURED",
            "ROTATION_DUE",
            "EXPIRED",
            "REVOKED",
            "INVALID",
        ]
    ]
):
    root: Literal[
        "NOT_REQUIRED",
        "MISSING",
        "CONFIGURED",
        "ROTATION_DUE",
        "EXPIRED",
        "REVOKED",
        "INVALID",
    ]


class ConnectivityState(
    RootModel[Literal["UNKNOWN", "ONLINE", "DEGRADED", "OFFLINE", "AUTH_FAILED", "CONFIG_ERROR"]]
):
    root: Literal["UNKNOWN", "ONLINE", "DEGRADED", "OFFLINE", "AUTH_FAILED", "CONFIG_ERROR"]


class ConnectionTestStatus(
    RootModel[Literal["QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED", "EXPIRED"]]
):
    root: Literal["QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED", "EXPIRED"]


class UploadLifecycleStatus(
    RootModel[
        Literal[
            "CREATED",
            "AUTHORIZING",
            "UPLOADING",
            "PAUSED",
            "FINALIZING",
            "PENDING_VERIFY",
            "VERIFYING",
            "AVAILABLE",
            "FAILED",
            "QUARANTINED",
            "CANCELLING",
            "CANCELLED",
            "EXPIRED",
        ]
    ]
):
    root: Literal[
        "CREATED",
        "AUTHORIZING",
        "UPLOADING",
        "PAUSED",
        "FINALIZING",
        "PENDING_VERIFY",
        "VERIFYING",
        "AVAILABLE",
        "FAILED",
        "QUARANTINED",
        "CANCELLING",
        "CANCELLED",
        "EXPIRED",
    ]


class VerificationStatus(
    RootModel[Literal["NOT_STARTED", "QUEUED", "RUNNING", "PASSED", "FAILED", "CANCELLED"]]
):
    root: Literal["NOT_STARTED", "QUEUED", "RUNNING", "PASSED", "FAILED", "CANCELLED"]


class PartStatus(
    RootModel[Literal["PLANNED", "UPLOADING", "OBSERVED", "SUCCEEDED", "FAILED", "ABORTED"]]
):
    root: Literal["PLANNED", "UPLOADING", "OBSERVED", "SUCCEEDED", "FAILED", "ABORTED"]


class ManifestStatus(RootModel[Literal["NOT_SUBMITTED", "RECEIVED", "PARSED", "INVALID"]]):
    root: Literal["NOT_SUBMITTED", "RECEIVED", "PARSED", "INVALID"]


class QuarantineDisposition(
    RootModel[
        Literal[
            "OPEN",
            "REVERIFY_REQUESTED",
            "RELEASED",
            "REPLACED",
            "SUPERSEDED",
            "RETENTION_EXPIRED",
        ]
    ]
):
    root: Literal[
        "OPEN",
        "REVERIFY_REQUESTED",
        "RELEASED",
        "REPLACED",
        "SUPERSEDED",
        "RETENTION_EXPIRED",
    ]


class UploadJobStatus(RootModel[Literal["QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED"]]):
    root: Annotated[
        Literal["QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED"],
        Field(
            description="Ingest-internal orchestration status used by existing command receipts; canonical public polling uses Platform Foundation AsyncJobStatus."
        ),
    ]


class CredentialInput1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["TOKEN"]
    token: Annotated[str, Field(min_length=1)]


class CredentialInput2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["BASIC"]
    username: Annotated[str, Field(min_length=1)]
    password: Annotated[str, Field(min_length=1)]


class CredentialInput3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["DEVICE_CERTIFICATE"]
    certificate_pem: Annotated[str, Field(min_length=1)]
    private_key_pem: Annotated[str, Field(min_length=1)]


class CredentialInput(RootModel[CredentialInput1 | CredentialInput2 | CredentialInput3]):
    root: CredentialInput1 | CredentialInput2 | CredentialInput3


class ConnectorConfiguration1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["ROBOT"]
    transport: Literal["HTTPS", "MQTTS"]
    endpoint_ref: Id
    safe_endpoint_hint: Annotated[str | None, Field(max_length=300)]
    tls_profile_id: str | None


class ConnectorConfiguration2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["EDGE_AGENT"]
    agent_id: Id
    transport: Literal["OUTBOUND_HTTPS", "MQTTS"]
    heartbeat_policy_id: Id


class ConnectorConfiguration3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["OSS_IMPORT"]
    oss_account_alias: Annotated[str, Field(max_length=100, min_length=1)]
    bucket_alias: Annotated[str, Field(max_length=100, min_length=1)]
    prefix_hint: Annotated[str, Field(max_length=300, min_length=1)]
    role_ref: Id
    source_region_code: Annotated[str, Field(min_length=1)]


class SafeProjection(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    display_name: Annotated[str | None, Field(max_length=200)]
    connector_family: Annotated[str | None, Field(max_length=100)]
    migration_hint: Annotated[str | None, Field(max_length=500)]


class ConnectorConfiguration4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["UNKNOWN"]
    raw_source_type: Annotated[str, Field(max_length=100, min_length=1)]
    safe_projection: SafeProjection


class ConnectorConfiguration(
    RootModel[
        ConnectorConfiguration1
        | ConnectorConfiguration2
        | ConnectorConfiguration3
        | ConnectorConfiguration4
    ]
):
    root: (
        ConnectorConfiguration1
        | ConnectorConfiguration2
        | ConnectorConfiguration3
        | ConnectorConfiguration4
    )


class WritableConnectorConfiguration1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["ROBOT"]
    transport: Literal["HTTPS", "MQTTS"]
    endpoint_ref: Id
    tls_profile_id: str | None


class WritableConnectorConfiguration2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["EDGE_AGENT"]
    agent_id: Id
    transport: Literal["OUTBOUND_HTTPS", "MQTTS"]
    heartbeat_policy_id: Id


class WritableConnectorConfiguration3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["OSS_IMPORT"]
    oss_account_alias: Annotated[str, Field(max_length=100, min_length=1)]
    bucket_alias: Annotated[str, Field(max_length=100, min_length=1)]
    prefix_hint: Annotated[str, Field(max_length=300, min_length=1)]
    role_ref: Id
    source_region_code: Annotated[str, Field(min_length=1)]


class WritableConnectorConfiguration(
    RootModel[
        WritableConnectorConfiguration1
        | WritableConnectorConfiguration2
        | WritableConnectorConfiguration3
    ]
):
    root: (
        WritableConnectorConfiguration1
        | WritableConnectorConfiguration2
        | WritableConnectorConfiguration3
    )


class RobotDataSourceBinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["ROBOT"]
    robot_id: Id
    display_name: Annotated[str | None, Field(max_length=200, min_length=1)]


class EdgeAgentDataSourceBinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["EDGE_AGENT"]
    agent_id: Id
    display_name: Annotated[str | None, Field(max_length=200, min_length=1)]


class OssImportDataSourceBinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["OSS_IMPORT"]
    source_alias: Annotated[str, Field(max_length=200, min_length=1)]
    display_name: Annotated[str | None, Field(max_length=200, min_length=1)]


class UnknownDataSourceBinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["UNKNOWN"]
    raw: Annotated[str, Field(max_length=100, min_length=1)]
    display_name: Annotated[str | None, Field(max_length=200, min_length=1)]


class DataSourceBinding(
    RootModel[
        RobotDataSourceBinding
        | EdgeAgentDataSourceBinding
        | OssImportDataSourceBinding
        | UnknownDataSourceBinding
    ]
):
    root: (
        RobotDataSourceBinding
        | EdgeAgentDataSourceBinding
        | OssImportDataSourceBinding
        | UnknownDataSourceBinding
    )


class WritableDataSourceBinding1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["ROBOT"]
    robot_id: Id


class WritableDataSourceBinding2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["EDGE_AGENT"]
    agent_id: Id


class WritableDataSourceBinding3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["OSS_IMPORT"]
    source_alias: Annotated[str, Field(max_length=200, min_length=1)]


class WritableDataSourceBinding(
    RootModel[WritableDataSourceBinding1 | WritableDataSourceBinding2 | WritableDataSourceBinding3]
):
    root: WritableDataSourceBinding1 | WritableDataSourceBinding2 | WritableDataSourceBinding3


class CredentialRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[str, Field(min_length=1)]
    provider: Annotated[str | None, Field(min_length=1)]
    credential_ref: Id | None
    state: CredentialState
    version: DecimalString
    masked_hint: Annotated[str | None, Field(max_length=100)]
    updated_at: IsoDateTime | None
    expires_at: IsoDateTime | None
    rotation_due_at: IsoDateTime | None


class CredentialSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[str, Field(min_length=1)]
    state: CredentialState
    credential_ref: Id | None
    masked_hint: Annotated[str | None, Field(max_length=100)]
    version: DecimalString
    updated_at: IsoDateTime | None
    expires_at: IsoDateTime | None
    rotation_due_at: IsoDateTime | None


class DataSourceSafeError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(max_length=100, min_length=1)]
    message: Annotated[str, Field(max_length=1000, min_length=1)]


class ConnectivitySummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    state: ConnectivityState
    last_check_state: Annotated[str, Field(max_length=100, min_length=1)]
    observed_config_version: DecimalString | None
    observed_credential_version: DecimalString | None
    checked_at: IsoDateTime | None
    safe_error: DataSourceSafeError | None


class DataSourceRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Id
    name: Annotated[str, Field(max_length=128, min_length=1)]
    source_type: Annotated[str, Field(max_length=100, min_length=1)]
    source_format: Annotated[str, Field(min_length=1)]
    configuration_version: DecimalString
    credential_version: DecimalString
    upload_policy_version: DecimalString


class WritableDataSourceRef(DataSourceRef):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_type: Literal["ROBOT", "EDGE_AGENT", "OSS_IMPORT"]


class Heartbeat(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    state: Literal["ONLINE", "DEGRADED", "OFFLINE", "NOT_APPLICABLE"]
    last_seen_at: IsoDateTime | None


class UploadPolicy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(min_length=1)]
    label: Annotated[str, Field(min_length=1)]
    max_object_size_bytes: DecimalString


class LastUpload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    upload_id: Id
    completed_at: IsoDateTime
    verified_bytes: DecimalString
    lifecycle_status: UploadLifecycleStatus


class AllowedAction(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class DataSource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Id
    scope: Scope
    name: Annotated[str, Field(max_length=128, min_length=1)]
    source_type: Annotated[str, Field(max_length=100, min_length=1)]
    source_format: Annotated[str, Field(min_length=1)]
    source_format_version: str | None
    adapter_version: Annotated[str | None, Field(min_length=1)]
    binding: DataSourceBinding
    configuration: ConnectorConfiguration
    administrative_state: AdministrativeState
    credential: CredentialSummary
    connectivity: ConnectivitySummary
    heartbeat: Heartbeat | None
    upload_policy: UploadPolicy
    last_upload: LastUpload | None
    config_version: DecimalString
    credential_version: DecimalString
    etag: ETag
    allowed_actions: list[AllowedAction]
    blocked_reasons: list[BlockedReason]
    created_at: IsoDateTime
    updated_at: IsoDateTime


class CreateDataSourceCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[str, Field(max_length=128, min_length=1)]
    source_type: Literal["ROBOT", "EDGE_AGENT", "OSS_IMPORT"]
    source_format: Annotated[str, Field(min_length=1)]
    source_format_version: str | None = None
    binding: WritableDataSourceBinding
    configuration: WritableConnectorConfiguration
    upload_policy_code: Annotated[str, Field(min_length=1)]
    credential_input: CredentialInput | None = None


class UpdateDataSourceCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[str, Field(max_length=128, min_length=1)]
    source_format: Annotated[str, Field(min_length=1)]
    source_format_version: str | None
    binding: WritableDataSourceBinding
    configuration: WritableConnectorConfiguration
    upload_policy_code: Annotated[str, Field(min_length=1)]
    change_reason: Annotated[str, Field(max_length=500, min_length=1)]


class RotateCredentialCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    credential_input: CredentialInput
    reason: Annotated[str, Field(max_length=500, min_length=1)]


class TestConnectionCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    observed_config_version: DecimalString
    observed_credential_version: DecimalString


class SourceStateCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reason: Annotated[str, Field(max_length=500, min_length=1)]
    expected_administrative_state: AdministrativeState


class ConnectionTest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    connection_test_id: Id
    source_id: Id
    status: ConnectionTestStatus
    observed_config_version: DecimalString
    observed_credential_version: DecimalString
    job_id: Id
    safe_error: SafeError | None
    created_at: IsoDateTime
    updated_at: IsoDateTime


class IngestJobResultRef1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    connection_test_id: Id | None = None
    upload_id: Id | None = None
    verification_run_id: Id | None = None
    quarantine_id: Id | None = None
    dataset_id: Id | None = None
    dataset_version_id: Id | None = None
    registration_receipt_id: Id | None = None


class IngestJobResultRef(RootModel[IngestJobResultRef1 | None]):
    root: Annotated[
        IngestJobResultRef1 | None,
        Field(
            description="Ingest-owned completion result projected into the canonical Platform Foundation AsyncJob result_ref; it is not a polling resource."
        ),
    ]


class Progress(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    completed: DecimalString
    total: DecimalString | None
    unit: Annotated[str, Field(min_length=1)]


class ResourceRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource_type: Literal["DATA_SOURCE", "UPLOAD_SESSION", "VERIFICATION_RUN"]
    resource_id: Id


class ObservedVersions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    config_version: DecimalString
    credential_version: DecimalString


class UploadJob(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Id
    type: Annotated[
        Literal[
            "DATA_SOURCE_CONNECTION_TEST",
            "UPLOAD_VERIFICATION",
            "UPLOAD_CANCEL",
            "UPLOAD_RECONCILIATION",
        ],
        Field(
            description="Domain value projected as kind in the canonical platform AsyncJob wire."
        ),
    ]
    status: UploadJobStatus
    stage: Annotated[str, Field(min_length=1)]
    progress: Progress
    resource_ref: ResourceRef
    observed_versions: ObservedVersions | None = None
    result_ref: IngestJobResultRef | None
    safe_error: SafeError | None
    etag: ETag
    allowed_actions: list[str]
    created_at: IsoDateTime
    updated_at: IsoDateTime


class UploadObjectDeclaration(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    client_object_id: Id
    relative_path: RelativePath
    size_bytes: DecimalString
    media_type: Annotated[str, Field(max_length=200, min_length=1)]
    last_modified_at: IsoDateTime | None
    declared_sha256: Sha256 | None


class DatasetTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Id
    name: Annotated[str, Field(max_length=200, min_length=1)]


class UploadResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dataset_id: Id
    dataset_version_id: Id
    dataset_version_status: Annotated[str, Field(min_length=1)]
    registration_receipt_id: Id
    verified_object_set_hash: Sha256
    source_manifest_id: Id
    source_manifest_sha256: Sha256
    adapter_version: Annotated[str, Field(min_length=1)]
    schema_ref: Id
    registered_at: IsoDateTime


class UploadProgress(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expected_bytes: DecimalString | None
    confirmed_received_bytes: DecimalString
    completed_parts: DecimalString
    total_parts: DecimalString | None
    completed_objects: DecimalString
    total_objects: DecimalString
    throughput_bytes_per_second: DecimalString | None
    estimated_remaining_seconds: DecimalString | None
    verification_stage: str | None


class UploadObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    object_id: Id
    relative_path: RelativePath
    source_role: Annotated[str, Field(min_length=1)]
    media_type: Annotated[str | None, Field(min_length=1)]
    size_bytes: DecimalString
    multipart_status: Literal[
        "DECLARED",
        "UPLOADING",
        "COMPLETED",
        "HASHING",
        "VERIFIED",
        "FAILED",
        "QUARANTINED",
    ]
    completed_parts: DecimalString
    total_parts: DecimalString | None
    etag: str | None
    declared_sha256: Sha256 | None
    verified_sha256: Sha256 | None
    checksum_status: Literal["NOT_CHECKED", "MATCHED", "MISMATCH"]
    verification_status: VerificationStatus
    resource_version: DecimalString
    updated_at: IsoDateTime
    allowed_actions: list[str]
    blocked_reasons: list[BlockedReason]


class Checksum(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    algorithm: Annotated[str, Field(min_length=1)]
    value: Annotated[str, Field(min_length=1)]
    status: Literal["NOT_CHECKED", "MATCHED", "MISMATCH"]


class UploadPart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    part_id: Id
    object_id: Id
    part_number: DecimalString
    attempt_count: DecimalString
    offset_bytes: DecimalString
    size_bytes: DecimalString
    status: PartStatus
    etag: str | None
    checksum: Checksum | None
    last_error: SafeError | None
    updated_at: IsoDateTime
    resource_version: DecimalString


class ManifestPart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    part_number: DecimalString
    provider_etag: Annotated[str, Field(min_length=1)]
    checksum_algorithm: Annotated[str, Field(min_length=1)]
    checksum_value: Annotated[str, Field(min_length=1)]


class ManifestObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    upload_object_id: Id
    relative_path: RelativePath
    size_bytes: DecimalString
    sha256: Sha256
    parts: Annotated[list[ManifestPart], Field(min_length=1)]


class SourceManifestPayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["source-upload-manifest/v1"]
    canonicalization: Literal["RFC8785"]
    hash_algorithm: Literal["SHA256"]
    source_format: Annotated[str, Field(min_length=1)]
    source_format_version: str | None
    objects: Annotated[list[ManifestObject], Field(min_length=1)]


class SchemaIssueCounts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: DecimalString
    warning: DecimalString
    info: DecimalString


class SourceManifest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    manifest_id: Id
    revision: DecimalString
    schema_version: Literal["source-upload-manifest/v1"]
    canonicalization: Literal["RFC8785"]
    sha256: Sha256
    object_set_hash: Sha256
    source_format: Annotated[str, Field(min_length=1)]
    source_format_version: str | None
    adapter_version: Annotated[str, Field(min_length=1)]
    declared_object_count: DecimalString
    declared_bytes: DecimalString
    submitted_by: ActorSummary
    submitted_at: IsoDateTime
    status: ManifestStatus
    schema_issue_counts: SchemaIssueCounts


class IssueCounts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: DecimalString
    warning: DecimalString
    info: DecimalString


class ManifestNode(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    node_id: Id
    parent_node_id: str | None
    json_pointer: Annotated[str, Field(pattern="^/")]
    node_type: Annotated[str, Field(min_length=1)]
    display_key: Annotated[str, Field(max_length=512, min_length=1)]
    value_summary: Annotated[str | None, Field(max_length=512)]
    child_count: DecimalString
    issue_counts: IssueCounts
    has_more_children: bool


class VerificationStage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Literal[
        "MANIFEST_SCHEMA",
        "OBJECT_EXISTENCE_SIZE",
        "OBJECT_SHA256",
        "ADAPTER_PARSE",
        "DATASET_SCHEMA_SEMANTIC",
        "ATOMIC_AVAILABILITY_COMMIT",
    ]
    status: Literal["PENDING", "RUNNING", "PASSED", "FAILED", "SKIPPED", "CANCELLED"]
    started_at: IsoDateTime | None
    finished_at: IsoDateTime | None
    job_id: str | None
    finding_count: DecimalString
    retryable: bool
    skip_reason: str | None


class FindingCounts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    info: DecimalString
    warning: DecimalString
    error: DecimalString


class VerificationRun(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    verification_run_id: Id
    supersedes_run_id: str | None
    object_set_hash: Sha256
    manifest_sha256: Sha256
    adapter_version: Annotated[str, Field(min_length=1)]
    schema_ref: Id | None = None
    status: VerificationStatus
    stages: Annotated[list[VerificationStage], Field(min_length=1)]
    finding_counts: FindingCounts
    job_id: Id
    started_at: IsoDateTime | None
    finished_at: IsoDateTime | None
    created_at: IsoDateTime
    resource_version: DecimalString


class VerificationFinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    finding_id: Id
    verification_run_id: Id
    severity: Literal["INFO", "WARNING", "ERROR"]
    code: Annotated[str, Field(min_length=1)]
    stage: Annotated[str, Field(min_length=1)]
    object_id: str | None
    safe_relative_path: RelativePath | None
    json_pointer: str | None
    expected_summary: Annotated[str | None, Field(max_length=512)]
    actual_summary: Annotated[str | None, Field(max_length=512)]
    retryable: bool
    message: Annotated[str, Field(max_length=1000, min_length=1)]
    request_id: Id
    created_at: IsoDateTime


class Quarantine(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    quarantine_id: Id
    upload_id: Id
    verification_run_id: Id
    object_set_hash: Sha256
    manifest_sha256: Sha256
    reason_code: Annotated[str, Field(min_length=1)]
    safe_summary: Annotated[str, Field(max_length=1000, min_length=1)]
    disposition: QuarantineDisposition
    retain_until: IsoDateTime
    created_at: IsoDateTime
    superseded_by_quarantine_id: str | None


class Actor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Annotated[str, Field(max_length=100, min_length=1)]
    id: str | None
    display_name: Annotated[str, Field(max_length=200, min_length=1)]


class ResourceRef1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[str, Field(min_length=1)]
    id: Id
    version: DecimalString


class SafePayload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    previous_status: str | None = None
    new_status: str | None = None
    reason_code: str | None = None
    stage: str | None = None
    object_id: str | None = None
    part_number: str | None = None
    attempt: str | None = None
    manifest_id: str | None = None
    verification_run_id: str | None = None
    quarantine_id: str | None = None
    supersedes_upload_id: str | None = None
    job_status: str | None = None
    retryable: bool | None = None


class UploadEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: Id
    event_type: Annotated[str, Field(pattern="^[a-z][a-z0-9_]*(?:[.][a-z0-9_]+)+$")]
    event_level: Literal["INFO", "WARNING", "ERROR"]
    occurred_at: IsoDateTime
    actor: Actor
    from_state: str | None
    to_state: str | None
    resource_ref: ResourceRef1
    job_id: str | None
    request_id: Id
    safe_payload: SafePayload


class PartSizeBytes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    minimum: DecimalString
    preferred: DecimalString
    maximum: DecimalString


class Concurrency(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    minimum: Annotated[int, Field(ge=1)]
    preferred: Annotated[int, Field(ge=1)]
    maximum: Annotated[int, Field(ge=1)]


class RetryableHttpStatus(RootModel[int]):
    root: Annotated[int, Field(ge=100, le=599)]


class Retry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_attempts_per_part: Annotated[int, Field(ge=1)]
    base_delay_ms: Annotated[int, Field(ge=0)]
    maximum_delay_ms: Annotated[int, Field(ge=0)]
    jitter_ratio: Annotated[float, Field(ge=0.0, le=1.0)]
    retryable_http_statuses: list[RetryableHttpStatus]


class Checksums(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    part_algorithm: Annotated[str, Field(min_length=1)]
    object_algorithm: Literal["SHA256"]
    require_object_sha256_before_manifest: Literal[True]


class Limits(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_object_count: DecimalString
    max_total_bytes: DecimalString
    max_object_bytes: DecimalString


class UploadPolicy1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal[1]
    policy_version: DecimalString
    effective_until: IsoDateTime
    part_size_bytes: PartSizeBytes
    concurrency: Concurrency
    retry: Retry
    checksums: Checksums
    limits: Limits


class Credentials(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    access_key_id: Annotated[str, Field(min_length=1)]
    access_key_secret: Annotated[str, Field(min_length=1)]
    security_token: Annotated[str, Field(min_length=1)]


class ShortUploadAuthorization(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    authorization_id: Id
    issued_at: IsoDateTime
    expires_at: IsoDateTime
    refresh_after: IsoDateTime
    oss_region: Annotated[str, Field(min_length=1)]
    endpoint: AnyUrl
    bucket: Annotated[str, Field(min_length=1)]
    object_prefix: Annotated[str, Field(min_length=1)]
    credentials: Credentials


class UploadObjectPlan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    upload_object_id: Id
    client_object_id: Id
    relative_path: RelativePath
    size_bytes: DecimalString
    multipart_upload_id: Annotated[str, Field(min_length=1)]
    object_key: Annotated[str, Field(min_length=1)]
    part_size_bytes: DecimalString
    confirmed_parts: list[ManifestPart]


class UploadHandoff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    authorization: ShortUploadAuthorization
    policy: UploadPolicy1 | None
    object_plans: list[UploadObjectPlan]


class UploadAuthorizationRenewalSecret(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    authorization: ShortUploadAuthorization
    replaces_authorization_id: Id
    policy: UploadPolicy1 | None


class UploadPartRetryPlanItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    upload_object_id: Id
    part_number: DecimalString
    offset_bytes: DecimalString
    size_bytes: DecimalString
    next_attempt: DecimalString
    not_before: IsoDateTime
    checksum_algorithm: Annotated[str, Field(min_length=1)]


class UploadPartRetrySecret(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    authorization: ShortUploadAuthorization


class ExpectedSourceVersions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    configuration_version: DecimalString
    credential_version: DecimalString
    upload_policy_version: DecimalString


class ClientCapabilities(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    supports_web_worker_hash: bool
    supports_crc64: bool
    supports_background_continuation: bool


class CreateUploadSessionCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source_id: Id
    target_dataset_id: Id | None
    source_format: Annotated[str, Field(min_length=1)]
    source_format_version: str | None
    expected_source_versions: ExpectedSourceVersions
    objects: Annotated[list[UploadObjectDeclaration], Field(min_length=1)]
    client_capabilities: ClientCapabilities


class RenewUploadAuthorizationCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expected_authorization_id: Id
    observed_resource_version: DecimalString
    reason: Literal["EXPIRING", "EXPIRED", "POLICY_REFRESH"]


class UploadStateCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expected_lifecycle_status: UploadLifecycleStatus
    reason: Annotated[str, Field(max_length=500, min_length=1)]


class ResumeUploadCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expected_lifecycle_status: UploadLifecycleStatus
    reason: Annotated[str, Field(max_length=500, min_length=1)]
    recovery_descriptor_version: DecimalString


class RequestedPart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    upload_object_id: Id
    part_number: DecimalString
    observed_attempt: DecimalString
    observed_error_code: Annotated[str, Field(min_length=1)]


class RetryUploadPartsCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    requested_parts: Annotated[list[RequestedPart], Field(min_length=1)]
    reason: Annotated[str, Field(max_length=500, min_length=1)]


class SubmitUploadManifestCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expected_object_set_hash: Sha256
    manifest_sha256: Sha256
    manifest: SourceManifestPayload


class RetryVerificationCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    failed_verification_run_id: Id
    expected_object_set_hash: Sha256
    expected_manifest_sha256: Sha256
    reason: Annotated[str, Field(max_length=500, min_length=1)]


class CreateReplacementUploadCommand(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reason: Annotated[str, Field(max_length=500, min_length=1)]
    replacement_reason_code: Annotated[str, Field(min_length=1)]
    target_dataset_id: Id | None
    objects: Annotated[list[UploadObjectDeclaration], Field(min_length=1)]


class CancelUploadCommand(RootModel[UploadStateCommand]):
    root: UploadStateCommand


class DatasetVersionRegistrationRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    registration_key: Annotated[str, Field(pattern="^registration:[a-f0-9]{64}$")]
    registration_intent_sha256: Sha256
    scope: Scope
    upload_id: Id
    target_dataset_id: Id | None
    verification_run_id: Id
    source_manifest_id: Id
    source_manifest_sha256: Sha256
    verified_object_set_hash: Sha256
    verified_object_count: DecimalString
    verified_bytes: DecimalString
    source_format: Annotated[str, Field(min_length=1)]
    source_format_version: str | None
    adapter_version: Annotated[str, Field(min_length=1)]
    schema_ref: Id
    schema_version: Annotated[str, Field(min_length=1)]
    source_snapshot: DataSourceRef
    request_id: Id
    idempotency_key_hash: Sha256


class DatasetVersionRegistrationReceipt(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dataset_id: Id
    dataset_version_id: Id
    dataset_version_status: Annotated[str, Field(min_length=1)]
    registration_receipt_id: Id
    scope: Scope
    upload_id: Id
    target_dataset_id: Id | None
    verification_run_id: Id
    source_manifest_id: Id
    source_manifest_sha256: Sha256
    verified_object_set_hash: Sha256
    verified_object_count: DecimalString
    verified_bytes: DecimalString
    source_format: Annotated[str, Field(min_length=1)]
    source_format_version: str | None
    adapter_version: Annotated[str, Field(min_length=1)]
    schema_ref: Id
    schema_version: Annotated[str, Field(min_length=1)]
    registered_at: IsoDateTime
    registration_key: Annotated[str, Field(pattern="^registration:[a-f0-9]{64}$")]
    registration_intent_sha256: Sha256


class DataSourceEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: DataSource
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class DataSourceSummaryMetrics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total_count: DecimalString
    online_count: DecimalString
    verified_bytes_today: DecimalString
    abnormal_count: DecimalString
    as_of: IsoDateTime
    timezone: Annotated[str, Field(max_length=100, min_length=1)]
    definition_version: Annotated[str, Field(max_length=100, min_length=1)]


class DataSourceFacetOption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    value: Annotated[str, Field(max_length=100, min_length=1)]
    label: Annotated[str, Field(max_length=200, min_length=1)]
    count: DecimalString


class DataSourceFacetRobot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Id
    name: Annotated[str, Field(max_length=200, min_length=1)]
    count: DecimalString


class DataSourceFacets(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_types: list[DataSourceFacetOption]
    source_formats: list[DataSourceFacetOption]
    robots: list[DataSourceFacetRobot]
    upload_policies: list[DataSourceFacetOption]
    administrative_states: list[DataSourceFacetOption]
    connectivity_states: list[DataSourceFacetOption]
    credential_states: list[DataSourceFacetOption]
    heartbeat_states: list[DataSourceFacetOption]


class DataSourcePageComponentError(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    component: Literal["SUMMARY", "FACETS", "ITEMS"]
    code: Annotated[str, Field(max_length=100, min_length=1)]
    message: Annotated[str, Field(max_length=1000, min_length=1)]
    retryable: bool
    request_id: str | None = None


class DataSourcePageEnvelope1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[DataSourceSummary] | None = None
    page_info: PageInfo | None = None
    component_errors: Any | None = None


class DataSourcePageEnvelope2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: Annotated[None, Field(None)] = None
    page_info: Annotated[None, Field(None)] = None
    component_errors: Any | None = None


class DecimalInteger(RootModel[ByteCount]):
    root: ByteCount


class UtcDateTime(RootModel[AwareDatetime]):
    root: AwareDatetime


class TraceId(RootModel[str]):
    root: Annotated[str, Field(pattern="^[0-9a-f]{32}$")]


class CorrelationId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1, pattern="^[A-Za-z0-9._:-]+$")]


class RequestId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1, pattern="^[A-Za-z0-9._:-]+$")]


class IdempotencyKey(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=16, pattern="^[A-Za-z0-9._:-]+$")]


class ETagModel(RootModel[str]):
    root: Annotated[str, Field(max_length=512, min_length=3)]


class OpaqueCursor(RootModel[str]):
    root: Annotated[str, Field(max_length=2048, min_length=1)]


class ScopeModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    organization_id: Annotated[str, Field(min_length=1)]
    project_id: Annotated[str | None, Field(min_length=1)] = None
    region_code: Annotated[str | None, Field(min_length=1)] = None


class ResourceRefModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource_type: Annotated[str, Field(pattern="^[a-z][a-z0-9_.-]{1,127}$")]
    resource_id: Annotated[str, Field(min_length=1)]
    version: str | None = None
    etag: ETagModel | None = None


class Link(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    rel: Annotated[str, Field(min_length=1)]
    href: str
    method: Literal["GET", "POST", "PUT", "PATCH", "DELETE"] | None = None


class ResponseMeta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    request_id: RequestId
    trace_id: TraceId
    correlation_id: CorrelationId
    generated_at: UtcDateTime
    as_of: UtcDateTime | None = None
    projection_version: str | None = None
    event_cursor: OpaqueCursor | None = None


class SuccessEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Any
    meta: ResponseMeta
    links: Annotated[list[Link], Field(validate_default=True)] = []


class FieldViolation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str
    code: Annotated[str, Field(pattern="^[A-Z][A-Z0-9_]{1,127}$")]
    message: str
    rejected_value: Any | None = None


class ProblemDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: str
    title: str
    status: Annotated[int, Field(ge=100, le=599)]
    detail: str | None = None
    instance: str | None = None


class ErrorEnvelopeModel(ProblemDetails):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(pattern="^[A-Z][A-Z0-9_]{1,127}$")]
    retryable: bool
    request_id: RequestId
    trace_id: TraceId
    correlation_id: CorrelationId
    occurred_at: UtcDateTime
    invalid_params: list[FieldViolation] | None = None
    current_etag: ETagModel | None = None
    retry_after_seconds: Annotated[int | None, Field(ge=0)] = None


class CursorPageMeta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    limit: Annotated[int, Field(ge=1, le=500)]
    has_more: bool
    next_cursor: OpaqueCursor | None = None
    previous_cursor: OpaqueCursor | None = None
    snapshot_token: OpaqueCursor | None = None
    as_of: UtcDateTime
    total_count: DecimalInteger | None = None


class PagedEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[Any]
    page: CursorPageMeta
    meta: ResponseMeta
    links: Annotated[list[Link], Field(validate_default=True)] = []


class AsyncJobStatus(
    RootModel[
        Literal[
            "QUEUED",
            "RUNNING",
            "SUCCEEDED",
            "FAILED",
            "CANCELLING",
            "CANCELLED",
            "EXPIRED",
        ]
    ]
):
    root: Annotated[
        Literal[
            "QUEUED",
            "RUNNING",
            "SUCCEEDED",
            "FAILED",
            "CANCELLING",
            "CANCELLED",
            "EXPIRED",
        ],
        Field(
            description="Canonical platform-wide AsyncJob status vocabulary. Domain contracts MUST reference this definition instead of declaring local job states."
        ),
    ]


class AsyncJobProgress(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    completed_units: DecimalInteger
    total_units: DecimalInteger | None = None
    unit: str | None = None
    percent: Annotated[float | None, Field(ge=0.0, le=100.0)] = None
    message: str | None = None


class AsyncJobResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource: ResourceRefModel | None = None
    result_kind: str | None = None
    expires_at: UtcDateTime | None = None


class SseEventEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_id: Annotated[str, Field(min_length=1)]
    cursor: OpaqueCursor
    event_type: Annotated[str, Field(pattern="^[a-z][a-z0-9_.-]{1,127}$")]
    emitted_at: UtcDateTime
    scope: ScopeModel
    sequence: DecimalInteger
    resource: ResourceRefModel | None = None
    data: Any
    trace_id: TraceId | None = None


class Data(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    server_time: UtcDateTime


class SseHeartbeat(SseEventEnvelope):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_type: Annotated[Literal["sse.heartbeat"], Field(pattern="^[a-z][a-z0-9_.-]{1,127}$")]
    data: Data


class SseResetRequiredData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reason: Literal[
        "CURSOR_EXPIRED", "RETENTION_GAP", "AUTHORIZATION_CHANGED", "PROJECTION_REBUILT"
    ]
    refetch_required: Literal[True]


class Data1(UploadJob):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[
        Literal["DATA_SOURCE_CONNECTION_TEST"],
        Field(
            description="Domain value projected as kind in the canonical platform AsyncJob wire."
        ),
    ]


class CursorPageEnvelopeBase(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Any]
    page_info: PageInfo
    snapshot_at: Annotated[
        IsoDateTime,
        Field(
            description="Snapshot timestamp shared by every item and page boundary in this response."
        ),
    ]
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class DataSourceCursorPageEnvelope(CursorPageEnvelopeBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Any]


class UploadSessionListEnvelope(CursorPageEnvelopeBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Any]


class Data2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    uploading_count: DecimalString
    verifying_count: DecimalString
    available_today_count: DecimalString
    failed_count: DecimalString
    uploaded_bytes_today: DecimalString
    as_of: IsoDateTime
    timezone: Annotated[str, Field(min_length=1)]
    definition_version: Annotated[str, Field(min_length=1)]


class UploadSessionMetricsEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data2
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class UploadCreationDataSourceOption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Id
    name: Annotated[str, Field(max_length=128, min_length=1)]
    source_type: Literal["ROBOT", "EDGE_AGENT", "OSS_IMPORT"]
    source_format: Annotated[str, Field(min_length=1)]
    configuration_version: DecimalString
    credential_version: DecimalString
    upload_policy_version: DecimalString
    allowed: bool
    blocked_reasons: list[BlockedReason]


class UploadCreationDatasetOption(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Id
    name: Annotated[str, Field(max_length=200, min_length=1)]
    allowed: bool
    blocked_reasons: list[BlockedReason]


class AllowedExtension(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9][a-z0-9._-]*$")]


class Format(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(min_length=1)]
    version: str | None
    adapter_version: Annotated[str, Field(min_length=1)]
    allowed_extensions: list[AllowedExtension]


class PolicySummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    policy_version: DecimalString
    label: Annotated[str, Field(max_length=200, min_length=1)]
    max_object_count: DecimalString
    max_total_bytes: DecimalString
    default_part_size_bytes: DecimalString
    max_concurrency: Annotated[int, Field(ge=1, le=64)]


class Data3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_sources: list[UploadCreationDataSourceOption]
    datasets: list[UploadCreationDatasetOption]
    formats: list[Format]
    policy_summaries: list[PolicySummary]
    allowed_actions: list[str]
    blocked_reasons: list[BlockedReason]


class UploadCreationOptionsEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data3
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class Data8(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    verification_run: VerificationRun


class UploadObjectPageEnvelope(CursorPageEnvelopeBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Any]


class UploadPartPageEnvelope(CursorPageEnvelopeBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Any]


class SourceManifestEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: SourceManifest
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class ManifestNodePageEnvelope(CursorPageEnvelopeBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Any]


class VerificationRunPageEnvelope(CursorPageEnvelopeBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Any]


class VerificationFindingPageEnvelope(CursorPageEnvelopeBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Any]


class UploadEventPageEnvelope(CursorPageEnvelopeBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Any]


class AdapterVersion(RootModel[str | None]):
    root: Annotated[str | None, Field(min_length=1)]


class AllowedActions(RootModel[list[AllowedAction]]):
    root: list[AllowedAction]


class Binding(RootModel[DataSourceBinding]):
    root: DataSourceBinding


class BlockedReasons(RootModel[list[BlockedReason]]):
    root: list[BlockedReason]


class ConfigVersion(RootModel[DecimalString]):
    root: DecimalString


class Connectivity(RootModel[ConnectivitySummary]):
    root: ConnectivitySummary


class CreatedAt(RootModel[IsoDateTime]):
    root: IsoDateTime


class Credential(RootModel[CredentialSummary]):
    root: CredentialSummary


class CredentialVersion(RootModel[DecimalString]):
    root: DecimalString


class Etag(RootModel[ETag]):
    root: ETag


class Name(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class SourceFormat(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class SourceFormatVersion(RootModel[str | None]):
    root: str | None


class SourceType(RootModel[str]):
    root: Annotated[str, Field(max_length=100, min_length=1)]


class UpdatedAt(RootModel[IsoDateTime]):
    root: IsoDateTime


class UploadPolicyModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(min_length=1)]
    label: Annotated[str, Field(min_length=1)]
    max_object_size_bytes: DecimalString


class DataSourceSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Id
    scope: Scope
    name: Name
    source_type: SourceType
    source_format: SourceFormat
    source_format_version: SourceFormatVersion | None
    adapter_version: AdapterVersion | None
    binding: Binding
    administrative_state: AdministrativeState
    credential: Credential
    connectivity: Connectivity
    heartbeat: Heartbeat | None
    upload_policy: UploadPolicyModel
    last_upload: LastUpload | None
    config_version: ConfigVersion
    credential_version: CredentialVersion
    etag: Etag
    allowed_actions: AllowedActions
    blocked_reasons: BlockedReasons
    created_at: CreatedAt
    updated_at: UpdatedAt


class UploadSession(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    upload_id: Id
    scope: Scope
    data_source: DataSourceRef
    target_dataset: DatasetTarget | None
    result: UploadResult | None
    supersedes_upload_id: str | None
    source_format: Annotated[str, Field(min_length=1)]
    source_format_version: str | None
    adapter_version: Annotated[str, Field(min_length=1)]
    lifecycle_status: UploadLifecycleStatus
    verification_status: VerificationStatus
    progress: UploadProgress
    source_manifest: SourceManifest | None
    latest_verification_run_id: str | None
    active_job_ids: list[Id]
    created_by: ActorSummary
    created_at: IsoDateTime
    updated_at: IsoDateTime
    etag: ETag
    resource_version: DecimalString
    allowed_actions: list[AllowedAction]
    blocked_reasons: list[BlockedReason]


class DataSourcePageEnvelope3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    summary: DataSourceSummaryMetrics | None
    facets: DataSourceFacets | None
    items: list[DataSourceSummary] | None
    page_info: Annotated[
        PageInfo | None,
        Field(
            description="Structured page boundaries for after/before traversal; null only when the ITEMS component has a matching error."
        ),
    ]
    snapshot_at: Annotated[
        IsoDateTime,
        Field(
            description="Snapshot timestamp shared by items and page_info; always present as a response field."
        ),
    ]
    allowed_actions: list[str]
    component_errors: Annotated[list[DataSourcePageComponentError], Field(max_length=3)]
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class DataSourcePageEnvelope4(DataSourcePageEnvelope1, DataSourcePageEnvelope3):
    model_config = ConfigDict(
        extra="forbid",
    )
    summary: DataSourceSummaryMetrics | None
    facets: DataSourceFacets | None
    items: list[DataSourceSummary] | None
    page_info: Annotated[
        PageInfo | None,
        Field(
            description="Structured page boundaries for after/before traversal; null only when the ITEMS component has a matching error."
        ),
    ]
    snapshot_at: Annotated[
        IsoDateTime,
        Field(
            description="Snapshot timestamp shared by items and page_info; always present as a response field."
        ),
    ]
    allowed_actions: list[str]
    component_errors: Annotated[list[DataSourcePageComponentError], Field(max_length=3)]
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class DataSourcePageEnvelope5(DataSourcePageEnvelope2, DataSourcePageEnvelope3):
    model_config = ConfigDict(
        extra="forbid",
    )
    summary: DataSourceSummaryMetrics | None
    facets: DataSourceFacets | None
    items: list[DataSourceSummary] | None
    page_info: Annotated[
        PageInfo | None,
        Field(
            description="Structured page boundaries for after/before traversal; null only when the ITEMS component has a matching error."
        ),
    ]
    snapshot_at: Annotated[
        IsoDateTime,
        Field(
            description="Snapshot timestamp shared by items and page_info; always present as a response field."
        ),
    ]
    allowed_actions: list[str]
    component_errors: Annotated[list[DataSourcePageComponentError], Field(max_length=3)]
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class DataSourcePageEnvelope6(DataSourcePageEnvelope1, DataSourcePageEnvelope3):
    model_config = ConfigDict(
        extra="forbid",
    )
    summary: DataSourceSummaryMetrics | None
    facets: DataSourceFacets | None
    items: list[DataSourceSummary] | None
    page_info: Annotated[
        PageInfo | None,
        Field(
            description="Structured page boundaries for after/before traversal; null only when the ITEMS component has a matching error."
        ),
    ]
    snapshot_at: Annotated[
        IsoDateTime,
        Field(
            description="Snapshot timestamp shared by items and page_info; always present as a response field."
        ),
    ]
    allowed_actions: list[str]
    component_errors: Annotated[list[DataSourcePageComponentError], Field(max_length=3)]
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class DataSourcePageEnvelope7(DataSourcePageEnvelope2, DataSourcePageEnvelope3):
    model_config = ConfigDict(
        extra="forbid",
    )
    summary: DataSourceSummaryMetrics | None
    facets: DataSourceFacets | None
    items: list[DataSourceSummary] | None
    page_info: Annotated[
        PageInfo | None,
        Field(
            description="Structured page boundaries for after/before traversal; null only when the ITEMS component has a matching error."
        ),
    ]
    snapshot_at: Annotated[
        IsoDateTime,
        Field(
            description="Snapshot timestamp shared by items and page_info; always present as a response field."
        ),
    ]
    allowed_actions: list[str]
    component_errors: Annotated[list[DataSourcePageComponentError], Field(max_length=3)]
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class DataSourcePageEnvelope8(DataSourcePageEnvelope1, DataSourcePageEnvelope3):
    model_config = ConfigDict(
        extra="forbid",
    )
    summary: DataSourceSummaryMetrics | None
    facets: DataSourceFacets | None
    items: list[DataSourceSummary] | None
    page_info: Annotated[
        PageInfo | None,
        Field(
            description="Structured page boundaries for after/before traversal; null only when the ITEMS component has a matching error."
        ),
    ]
    snapshot_at: Annotated[
        IsoDateTime,
        Field(
            description="Snapshot timestamp shared by items and page_info; always present as a response field."
        ),
    ]
    allowed_actions: list[str]
    component_errors: Annotated[list[DataSourcePageComponentError], Field(max_length=3)]
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class DataSourcePageEnvelope9(DataSourcePageEnvelope2, DataSourcePageEnvelope3):
    model_config = ConfigDict(
        extra="forbid",
    )
    summary: DataSourceSummaryMetrics | None
    facets: DataSourceFacets | None
    items: list[DataSourceSummary] | None
    page_info: Annotated[
        PageInfo | None,
        Field(
            description="Structured page boundaries for after/before traversal; null only when the ITEMS component has a matching error."
        ),
    ]
    snapshot_at: Annotated[
        IsoDateTime,
        Field(
            description="Snapshot timestamp shared by items and page_info; always present as a response field."
        ),
    ]
    allowed_actions: list[str]
    component_errors: Annotated[list[DataSourcePageComponentError], Field(max_length=3)]
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class DataSourcePageEnvelope(
    RootModel[
        DataSourcePageEnvelope4
        | DataSourcePageEnvelope5
        | DataSourcePageEnvelope6
        | DataSourcePageEnvelope7
        | DataSourcePageEnvelope8
        | DataSourcePageEnvelope9
    ]
):
    root: (
        DataSourcePageEnvelope4
        | DataSourcePageEnvelope5
        | DataSourcePageEnvelope6
        | DataSourcePageEnvelope7
        | DataSourcePageEnvelope8
        | DataSourcePageEnvelope9
    )


class AsyncJob(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    job_id: Annotated[str, Field(min_length=1)]
    kind: Annotated[
        str,
        Field(
            description="Domain-owned job type discriminator projected into the canonical platform wire.",
            max_length=128,
            min_length=1,
        ),
    ]
    status: AsyncJobStatus
    stage: Annotated[
        str,
        Field(
            description="Domain-owned execution stage identifier; it does not extend the platform status vocabulary.",
            max_length=128,
            min_length=1,
        ),
    ]
    progress: AsyncJobProgress | None
    result_ref: Annotated[
        dict[constr(pattern=r"^[a-z][a-z0-9_]*_id$"), str] | None,
        Field(
            description="Opaque domain-owned result identifiers only; the Job wire never embeds a domain result body."
        ),
    ]
    error: ErrorEnvelopeModel | None
    scope: ScopeModel
    resource_ref: Annotated[
        ResourceRefModel,
        Field(
            description="Owning resource identity used for authorization derivation and domain result lookup."
        ),
    ]
    created_at: UtcDateTime
    started_at: UtcDateTime | None = None
    finished_at: UtcDateTime | None = None
    updated_at: UtcDateTime
    expires_at: UtcDateTime | None = None
    etag: ETagModel
    cancellable: bool
    retry_of_job_id: str | None = None


class AsyncJobAcceptedEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: AsyncJob
    meta: ResponseMeta
    links: Annotated[list[Link], Field(min_length=1)]


class SseResetRequired(SseEventEnvelope):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_type: Annotated[
        Literal["stream.reset_required"], Field(pattern="^[a-z][a-z0-9_.-]{1,127}$")
    ]
    data: SseResetRequiredData


class ConnectionTestJobEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data1
    job: AsyncJob
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class UploadSessionEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: UploadSession
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class Data4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session: UploadSession
    objects: list[UploadObject]
    latest_verification_run: VerificationRun | None
    latest_quarantine: Quarantine | None
    active_jobs: list[UploadJob]


class UploadSessionBootstrapEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data4
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class Data5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    upload_session: UploadSession
    secret: UploadHandoff


class UploadHandoffEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data5
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class Data6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    upload_session: UploadSession
    secret: UploadAuthorizationRenewalSecret


class UploadAuthorizationRenewalEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data6
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class Data7(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session: UploadSession
    retry_plan: list[UploadPartRetryPlanItem]
    secret: UploadPartRetrySecret


class UploadPartRetryEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data7
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class VerificationRunJobEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: Data8
    job: AsyncJob
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]


class UploadJobEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: UploadJob
    job: AsyncJob
    scope: Scope
    request_id: Id
    contract_version: Literal["ingest.v1alpha1"]
